name: formsflowai_shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_easyloading: ^3.0.3
  google_fonts: ^3.0.1
  flutter_inappwebview: ^5.4.3+7
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.4.0
  hooks_riverpod: ^1.0.3
  motion_toast: ^2.1.9
  flutter_hooks: ^0.18.2+1
  logger: ^1.1.0
  floor: ^1.1.0
  go_router: ^3.1.0
  sizer: ^2.0.15
  visibility_detector: ^0.3.3


  # internal packages
  formsflowai_api:
    path: ../formsflowai_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: any
  build_runner: ^2.1.11


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.


  # To add assets to your application, add an assets section, like this:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

#  fonts:
#    - family: Montserrat
#      fonts:
#        - asset: font/Montserrat_Regular.ttf
#          weight: 400
#        - asset:  font/Montserrat_Medium.ttf
#          weight: 500
#        - asset: font/Montserrat_Bold.ttf
#          weight: 700
#        - asset:  font/Montserrat_SemiBold.ttf
#          weight: 600


