name: "build-android"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
      - release/**
  pull_request:
    branches:
      - develop
      - main
      - release/**

jobs:
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

        # Getting  Flutter dependencies
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run build_runner build


        # Flutter analyze
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .

      # Build flutter APK.
      - run: flutter build apk --release

      # Uploading APK to artifacts.

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk



